name: 'Validate Terraform'

on:
  push:
    branches:
       - main

  pull_request:
  workflow_dispatch: 

jobs:
  terraform:
    name: 'Validate terraform.'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.NIHR_DEVELOPMENT_IAM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.NIHR_DEVELOPMENT_IAM_ACCESS_KEY_SECRET }}
        aws-region: eu-west-2

    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform Init
      run: |
           terraform init --backend=false

    - name: Terraform Format
      run: |
            terraform fmt
        
    - name: Terraform Validate
      run: |
           terraform validate
