name: 'Validate Terraform'

on:
  push:
    branches:
       - main

  pull_request:
  workflow_dispatch: 

jobs:
  validate:
    uses: PA-NIHR-CRN/github-shared-workflows-and-actions/.github/workflows/validate-terraform.yml@feature/set-up-repo
    secrets: inherit
    with:
      path: ecs
